---
- name: Revert to a snapshot
  community.vmware.vmware_guest_snapshot:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    folder: "{{ folder_path }}"
    name: "{{ vm_name }}"
    state: revert
    snapshot_name: "{{ snap_name }}"
  delegate_to: localhost